#import = ["~/.config/sesh/configs/nu-sesh.toml"]

[default_session]
startup_command = "nvim +GoToFile"

# TODO: potential feature ideas
# [[session]]
# name = "session"
# path = "~/path/to/session"
# startup_script = "~/git_repos/dotfiles/sesh/bin/spotify.sh"
# detached = true # never attach to this session, just create it in the background
# tmuxp = "~/.config/tmux/tmuxp/joshmedeski.com.yml"
# tmuxinator = "~/.config/tmux/tmuxinator/joshmedeski.com.yml"
#

[[session]]
name = "wingman_spirit"
path = "~/Documents/git/wingman_modules/wingman_spirit"
startup_script = "~/.config/sesh/scripts/wingman_spirit"

[[session]]
name = "dumps_replayer"
path = "~/Documents/git/wingman_modules/wingman_dumps_replay/"

[[session]]
name = "wingman_cloud"
path = "~/Documents/git/wingman_modules/wingman_cloud/"

[[session]]
name = "dotfiles"
path = "~/.config/"

[[session]]
name = "mantiq_workflows"
path = "~/Documents/git/mantiq_workflows/"

[[session]]
name = "wingman_ansible"
path = "~/Documents/git/wingman_modules/wingman_ansible/"

[[session]]
name = "exchange_property"
path = "/home/adrian/Documents/git/exchange_property_www"

[[session]]
name = "kubernetes"
path = "/home/adrian/Documents/git/equitanata_kubernetes"

[[session]]
name = "infrastructure_monitoring"
path = "/home/adrian/Documents/git/infrastructure_monitoring"

[[session]]
name = "erp"
path = "/home/adrian/Documents/git/intranet_modules/erp"

[[session]]
name = "mantiq_utils"
path = "/home/adrian/Documents/git/intranet_modules/mantiq_utils"
